apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: fl304fd6o-nodejs
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: fl304fd6o-nodejs 
  name: fl304fd6o-nodejs
spec:
  ports:
  - port: 3001 
    targetPort: 3001 
  selector:
    app.kubernetes.io/instance: fl304fd6o-nodejs 
